version: 2

sources:
  - name: staging
    database: ny-rides-stavros-zoomcamp
    schema: trips_data_all

    tables:
      - name: green_tripdata_2019_non_partitioned
      - name: green_tripdata_2020_non_partitioned
      - name: yellow_tripdata_2019_non_partitioned
      - name: yellow_tripdata_2020_non_partitioned
      - name: fhv_tripdata_2019_non_partitioned

